config/routes.rb
Espresso::Engine.routes.draw do

  resources :assets do
    collection { get :thumbnails }
  end
  resources :sections, :except => :show

  resources :articles do
    member { put :publish }
  end

  match 'icons/*ctype/:size' => 'icons#show', :as => 'icon', :constraints => { :size => /\d+/ }

  root :to => 'articles#index'
end

app/models/espresso/article.rb
require 'rdiscount'
require 'coderay'

require 'espresso/concerns/taggable'

module Espresso
  class Article < ActiveRecord::Base
    include Concerns::Taggable

    belongs_to :section, :class_name => "Espresso::Section"
    #has_and_belongs_to_many :tags, :class_name => 'Espresso::Tag', :join_table => "espresso_taggings", :as => :taggable
    has_many :comments, :class_name => "Espresso::Comment", :foreign_key => "article_id",
                        :order => 'created_at ASC', :dependent => :destroy

    attr_accessor :publish

    attr_accessible :title, :body, :slug, :section_id, :publish

    validates :title, :presence => true
    validates :slug, :presence => true, :unless => 'title.blank?'
    validates :path, :presence => true, :uniqueness => true
    validates :body, :presence => true
    validates :body_html, :presence => true
    validates :section_id, :presence => true

    before_validation :update_body_html
    before_validation :set_default_section
    before_validation :update_slug_and_path
    before_validation :publish_if_checkbox_checked

    scope :published, lambda{ where('published_at IS NOT NULL AND published_at <= ?', Time.now) }
    scope :for_year, lambda { |year|
      beg_of_year = Time.parse("#{year}-01-01")
      where('published_at between ? AND ?', beg_of_year, beg_of_year.end_of_year)
    }

    delegate :show_pub_date?, :to => :section

    def publish!
      update_attribute :published_at, Time.now
    end

    def published?
      published_at.present? && published_at <= Time.now
    end

    def self.[](path)
      published.find_by_path(path)
    end

    protected

    def publish_if_checkbox_checked
      self.published_at = Time.now if ['1', true, 'true'].include?(publish) && !self.published_at.present?
    end

    def set_default_section
      self.section = Section.root if section_id.blank? && section.blank?
    end

    def update_body_html
      self.body_html = RDiscount.new(code_ray(body)).to_html
    end

    def code_ray(text)
      text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
        CodeRay.scan($3, $2).div
      end
    end

    def update_slug_and_path
      self.slug = title.sluganize if slug.blank?
      self.path = "#{section.path}/#{slug}".gsub(/^\//, '')
    end

  end
end

app/models/espresso/asset.rb
require 'espresso/concerns/taggable'
require 'espresso/concerns/image_scaling'

module Espresso
  class Asset < ActiveRecord::Base
    include Espresso::Engine.routes.url_helpers
    include ActionView::Helpers::NumberHelper
    include Concerns::Taggable
    include Concerns::ImageScaling

    attr_accessible :title, :file, :remote_file_url, :file_cache
    mount_uploader :file, AssetUploader

    validates :file, :presence => true
    validates :file_size, :numericality => { :greater_than => 0 }

    scope :by_date, order('created_at DESC')

    def full_file_url(request)
      URI::Generic.build(scheme:request.scheme, host:request.host, port:request.port, path:file_url).to_s
    end

    def to_jq_upload(request)
      {
        "name" => read_attribute(:file),
        "size" => number_to_human_size(file_size),
        "url" => full_file_url(request),
        "thumbnail_url" => file.thumb.url,
        "edit_url" => edit_asset_path(self),
        "delete_url" => asset_path(self),
        "updated_at" => I18n.l(updated_at, :format => :long)
      }
    end

    def unscaled_path
      file.current_path
    end

    def content_type
      read_attribute(:content_type) || 'application/octet-stream'
    end

    def image?
      content_type =~ /image/
    end
  end
end

app/models/espresso/comment.rb
require 'rdiscount'

module Espresso
  class Comment < ActiveRecord::Base
    belongs_to :article, :class_name => "Espresso::Article", :foreign_key => "article_id"
    attr_accessible :author_name, :author_url, :author_email, :body

    validates :author_name, :presence => true
    validates :body, :presence => true
    validates :body_html, :presence => true

    before_validation :update_body_html

    scope :approved, where(:approved => true)

    private

    def update_body_html
      self.body_html = RDiscount.new(body).to_html
    end

  end
end

app/models/espresso/section.rb
module Espresso
  class Section < ActiveRecord::Base

    acts_as_nested_set :dependent => :destroy

    has_many :articles, :class_name => "Espresso::Article",
                        :foreign_key => "section_id",
                        :dependent => :destroy

    attr_accessible :name, :parent_id, :show_pub_date

    validates :name, :presence => true
    validates :slug, :format => /[\w-]+/, :allow_blank => true
    validates :path, :uniqueness => true

    before_validation :update_slug_and_path
    after_save :sort_rank

    scope :ordered, order('lft ASC')

    def self.[](path)
      find_by_path path
    end

    def self.root
      s = find_or_create_by_name_and_slug('ROOT', '')
      if s.persisted?
        s
      else
        raise "could not create root section: #{s.errors.full_messages}"
      end
    end

    def root?
      parent_id.nil? && slug.blank? && name == 'ROOT'
    end

    def empty?
      articles.blank?
    end


    protected

    # after inserting a new node, move it to the correct position so slugs on this level stay
    # ordered alphabetically.
    def sort_rank
      node = self
      previous_node = nil
      while node = node.left_sibling
        break if node.slug < slug
        previous_node = node
      end
      if node
        move_to_right_of node
      elsif previous_node
        move_to_left_of previous_node
      end
    end

    def update_slug_and_path
      self.slug = name.sluganize if !root?
      self.path = "#{parent.path + '/' if parent}#{slug}".gsub(/^\//, '')
    end

  end
end

app/models/espresso/tag.rb
module Espresso
  class Tag < ActiveRecord::Base
    has_and_belongs_to_many :articles, :join_table => "espresso_taggings"
  end
end

app/models/espresso/tagging.rb
module Espresso
  class Tagging < ActiveRecord::Base
    attr_accessible :tag_id, :taggable_id, :taggable_type

    belongs_to :tag, :class_name => 'Espresso::Tag'
    belongs_to :taggable, :polymorphic => true
  end
end

app/controllers/espresso/application_controller.rb
module Espresso
  class ApplicationController < ActionController::Base

    layout 'espresso/application'

    protected

    def find_sections
      Section.root # ensure the root section exists
      # @sections = Section.root.hierarchy
      @sections = Section.order('lft ASC')
    end

  end
end

app/controllers/espresso/articles_controller.rb
module Espresso
  class ArticlesController < Espresso::ApplicationController
    before_filter :find_article, :only => %w(show edit update destroy publish)
    before_filter :find_sections, :only => %w(new edit update create)

    def index
      @articles = Article.order('created_at DESC').page(params[:page])
    end

    def show
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new params[:article]
      if @article.save
        redirect_to articles_url, :notice => t('espresso.flash.articles.created')
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      if @article.update_attributes(params[:article])
        redirect_to articles_url, :notice => t('espresso.flash.articles.updated')
      else
        render 'edit'
      end
    end

    def publish
      @article.publish!
      redirect_to articles_url, :notice => t('espresso.flash.articles.published')
    end

    def destroy
      @article.destroy
      redirect_to articles_url, :notice => t('espresso.flash.articles.destroyed')
    end

    private

    def find_article
      @article = Article.find params[:id]
    end

  end
end

app/controllers/espresso/assets_controller.rb
module Espresso
  class AssetsController < ApplicationController
    before_filter :find_asset, :only => %w(edit update destroy)

    def index
      @assets = Asset.by_date.page(params[:page])
      render 'index'
    end

    def thumbnails
      @assets = Asset.by_date.page(params[:page])
    end

    def edit
    end

    def update
      if @asset.update_attributes(params[:asset])
        redirect_to assets_url, :notice => t('espresso.flash.assets.updated')
      else
        render 'edit'
      end
    end

    def create
      if params[:asset]
        # standard form
        @asset = Asset.new params[:asset]
        if @asset.save
          redirect_to assets_url(:view => params[:view], :page => params[:page]), :notice => t('espresso.flash.assets.created')
        else
          logger.error @asset.errors.full_messages
          index
        end
      elsif params[:files]
        # jquery multi-file-upload
        json = params[:files].map do |file|
          Asset.create :file => file
        end.map do |asset|
          asset.to_jq_upload request
        end.to_json
        respond_to do |format|
          format.html {
            # support iframe upload for crappy browsers
            render :json => json, :content_type => 'text/html', :layout => false
          }
          format.json {
            render :json => json
          }
        end
      else
        redirect_to assets_url
      end
    end

    def destroy
      @asset.destroy
      redirect_to assets_url, :notice => t('espresso.flash.assets.destroyed')
    end

    private

    def find_asset
      @asset = Asset.find params[:id]
    end
  end
end

app/controllers/espresso/icons_controller.rb
require 'open-uri'

module Espresso
  class IconsController < ApplicationController
    caches_page :show

    def show
      data = open "http://www.stdicon.com/crystal/#{params[:ctype]}?size=#{params[:size]}"
      send_data data.read, :type => data.content_type
    end

  end
end

app/controllers/espresso/sections_controller.rb
module Espresso
  class SectionsController < ApplicationController
    before_filter :find_section, :only => %w(edit update destroy)
    before_filter :find_sections, :only => %w(index new edit update create)

    def index
      @sections = @sections.page(params[:page])
    end

    def edit
    end

    def update
      if @section.update_attributes(params[:section])
        redirect_to sections_path, :notice => t('espresso.flash.sections.updated')
      else
        render 'edit'
      end
    end

    def new
      @section = Section.new :parent_id => params[:parent_id]
    end

    def create
      @section = Section.new params[:section]
      if @section.save
        redirect_to sections_path, :notice => t('espresso.flash.sections.created')
      else
        render 'new'
      end
    end

    def destroy
      if @section.destroy
        redirect_to sections_path, :notice => t('espresso.flash.sections.destroyed')
      else
        redirect_to sections_path, :alert => t('espresso.flash.sections.not_destroyed')
      end
    end

    private

    def find_section
      @section = Section.find params[:id]
    end

  end
end

app/helpers/espresso/application_helper.rb
module Espresso
  module ApplicationHelper
  end
end

app/helpers/espresso/articles_helper.rb
module Espresso
  module ArticlesHelper
  end
end

app/helpers/espresso/assets_helper.rb
module Espresso
  module AssetsHelper
    def small_thumb(asset)
      thumbnail asset, :thumb, 50
    end

    def large_thumb(asset)
      thumbnail asset, :large_thumb, 120
    end


    def thumbnail(asset, size_type, size_px)
      url = asset.file.is_image?(asset) ?
        asset.file_url(size_type) :
        icon_path(:ctype => asset.content_type, :size => size_px)
 #       "http://www.stdicon.com/crystal/#{asset.content_type}?size=#{size_px}"
      link_to image_tag(url, :alt => asset.title),
              edit_asset_path(asset),
              :download => asset.full_file_url(request),
              :title => asset.title, :class => 'download'

    end
  end
end

app/helpers/espresso/sections_helper.rb
module Espresso
  module SectionsHelper
  end
end

app/views/espresso/assets/_asset.html.erb
<tr>
  <td class="preview">
    <%= small_thumb asset %>
  </td>
  <td><%= link_to asset.title, edit_asset_path(asset) %></td>
  <td> <%= number_to_human_size asset.file_size %> </td>
  <td> <%= l asset.updated_at, :format => :long %> </td>
  <td class="buttons">
    <%= link_to '<i class="icon-trash icon-white"></i> '.html_safe + t('.button.delete'),
                asset, :method => :delete, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/espresso/assets/_form.html.erb
<%= f.text_field :title, :class => 'input-xlarge' %>
<%= f.text_field :tag_names, :class => 'input-xlarge' %>
<%= f.file_field(:file) do %>
  <%#= image_tag(f.object.file_url(:thumb)) if f.object.file? %>
<% end %>
<%= f.hidden_field :file_cache %>

app/views/espresso/assets/_js_upload_form.html.erb
<div class="row fileupload-buttonbar">
    <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="icon-plus icon-white"></i>
            <span>Add files...</span>
            <input type="file" name="files[]" multiple>
        </span>
        <button type="submit" class="btn btn-primary start">
            <i class="icon-upload icon-white"></i>
            <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
            <i class="icon-ban-circle icon-white"></i>
            <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
            <i class="icon-trash icon-white"></i>
            <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
    </div>
    <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
            <div class="bar" style="width:0%;"></div>
        </div>
    </div>
</div>
<!-- The loading indicator is shown during image processing -->
<div class="fileupload-loading"></div>
<br>
<!-- The table listing the files available for upload/download -->
<table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>

app/views/espresso/assets/_subnav.html.erb
<div class="row">
  <div class="span12">
    <ul class="nav nav-tabs">
      <li class="<%= 'active' if params[:action] == 'index' %>" >
        <%= link_to t('.tabular'), assets_path %>
      </li>
      <li class="<%= 'active' if params[:action] == 'thumbnails' %>" >
        <%= link_to t('.thumbnails'), thumbnails_assets_path %>
      </li>
    </ul>
  </div>
</div>

app/views/espresso/assets/_thumbnail.html.erb
<li class="span2">
  <div class="thumbnail">
    <%= large_thumb thumbnail %>
    <h5> <%= thumbnail.title %> </h5>
    <p> <%= number_to_human_size thumbnail.file_size %> </p>
  </div>
</li>

app/views/espresso/assets/edit.html.erb
<%= render 'subnav' %>

<div class="row">
  <div class="span8">
    <%= link_to image_tag(@asset.file_url(:large)), @asset.file_url %>
  </div>
  <div class="span4">
    <%= twitter_bootstrap_form_for @asset, :html => {:multipart => true} do |f| %>
      <%= f.fieldset t('.legend.edit_asset') do %>
        <%= render 'form', :f => f %>
      <% end %>

      <div class="form-actions">
        <%= f.submit t('.button.save'), :class => 'btn btn-primary' %>
        <%= link_to t('.button.cancel'), assets_url, :class => 'btn' %>
      </div>
    <% end %>
  </div>

</div>

app/views/espresso/assets/index.html.erb
<%= render 'subnav' %>

<div class="row">
  <div class="span8">
    <%= paginate @assets, :theme => 'tw_bootstrap' %>
    <table class="table table-striped">
      <colgroup>
        <col width="15%" />
        <col width="*" />
        <col width="15%" />
        <col width="15%" />
        <col width="20%" />
      </colgroup>
      <thead>
        <tr>
          <th> <%= t '.th.preview' %> </th>
          <th> <%= t '.th.title' %> </th>
          <th> <%= t '.th.size' %> </th>
          <th> <%= t '.th.updated_at' %> </th>
          <th></th>
        </tr>
      </thead>
      <tbody class="files">
        <%= render @assets %>
      </tbody>
    </table>
    <%= paginate @assets, :theme => 'tw_bootstrap' %>
  </div>

  <div class="span4">
    <%= twitter_bootstrap_form_for Espresso::Asset.new, :html => {:multipart => true} do |f| %>

      <div class="fileupload-buttonbar">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="icon-plus icon-white"></i>
            <span>Add files...</span>
            <input type="file" name="files[]" multiple />
        </span>

        <button type="reset" class="btn btn-warning cancel">
            <i class="icon-ban-circle icon-white"></i>
            <span>Cancel all uploads</span>
        </button>
        <p> <%= t '.label.or_just_drag' %> </p>

      </div>

    <% end %>
  </div>

</div>


<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name">
        <span>{%=file.name%}</span>
      </td>
      <td class="size">
        <span>{%=o.formatFileSize(file.size)%}</span>
      </td>
      {% if (file.error) { %}
        <td class="error">
          <span class="label label-important">{%=locale.fileupload.error%}</span>
          {%=locale.fileupload.errors[file.error] || file.error%}
        </td>
      {% } else if (o.files.valid && !i) { %}
        <td>
          <div class="progress progress-success progress-striped active">
            <div class="bar" style="width:0%;"></div>
          </div>
        </td>
      {% } else { %}
        <td></td>
      {% } %}
      <td class="buttons cancel">
        {% if (!i) { %}
          <button class="btn btn-warning btn-mini">
            <i class="icon-ban-circle icon-white"></i>
            <span>{%=locale.fileupload.cancel%}</span>
          </button>
        {% } %}
      </td>
    </tr>
{% } %}
</script>

<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
          <td></td>
          <td class="name">{%=file.name%}</td>
          <td class="size">{%=o.formatFileSize(file.size)%}</td>
          <td class="error">
            <span class="label label-important">{%=locale.fileupload.error%}</span>
            {%=locale.fileupload.errors[file.error] || file.error%}
          </td>
        {% } else { %}
          <td class="preview">
            {% if (file.thumbnail_url) { %}
              <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}">
                <img src="{%=file.thumbnail_url%}" alt="{%=file.name%}" />
              </a>
            {% } %}
          </td>
          <td class="name">
            <a href="{%=file.edit_url%}">{%=file.name%}</a>
          </td>
          <td class="size"> {%=file.size%} </td>
          <td> {%=file.updated_at%} </td>
        {% } %}
        <td class="buttons">
          <a href="{%=file.delete_url%}" class="btn btn-danger btn-mini" data-method="delete">
            <i class="icon-trash icon-white"></i>
            {%=locale.fileupload.destroy%}
          </a>
        </td>
    </tr>
{% } %}
</script>

<%= javascript_tag do %>
window.locale = {
    "fileupload": {
        "errors": {
            "maxFileSize": "File is too big",
            "minFileSize": "File is too small",
            "acceptFileTypes": "Filetype not allowed",
            "maxNumberOfFiles": "Max number of files exceeded",
            "uploadedBytes": "Uploaded bytes exceed file size",
            "emptyResult": "Empty file upload result"
        },
        "error": "Error",
        "start": "Start",
        "cancel": "Cancel",
        "destroy": "Delete"
    }
};
<% end %>

app/views/espresso/assets/thumbnails.html.erb
<%= render 'subnav' %>

<div class="row">
  <div class="span12">
    <% if @assets.any? %>
      <%= paginate @assets, :theme => 'tw_bootstrap' %>
      <ul class="thumbnails">
        <%= render :partial => 'thumbnail', :collection => @assets %>
      </ul>
      <%= paginate @assets, :theme => 'tw_bootstrap' %>
    <% else %>
      <p class="well"> <%= t '.p.no_assets' %> </p>
    <% end %>
  </div>
</div>